# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PastHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('identity_number', models.CharField(db_index=True, max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('average_monthly_income', models.CharField(blank=True, max_length=30, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('blood_type', models.CharField(max_length=1)),
                ('hospital_records', models.CharField(blank=True, max_length=100, null=True)),
                ('complaint', models.CharField(blank=True, max_length=100, null=True)),
                ('food_allergy_history', models.CharField(blank=True, max_length=100, null=True)),
                ('medicine_allergy_history', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='pasthistory',
            name='people',
            field=models.ManyToManyField(to='people.People'),
        ),
        migrations.AddField(
            model_name='contact',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.People'),
        ),
    ]
